export const productData = [
    {
        id: 1,
        src: "./gh-baby-1.webp",
        title: "Áo Thun Dài Tay Nam",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 2,
        src: "./gh-baby-2.webp",
        title: "Áo Thun Dài Tay Nam",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 3,
        src: "./gh-baby-3.webp",
        title: "Áo Thun Dài Tay Nam",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 4,
        src: "./gh-baby-4.webp",
        title: "Áo Thun Dài Tay Nữ",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 5,
        src: "./gh-baby-5.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 6,
        src: "./gh-baby-6.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 7,
        src: "./gh-baby-7.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 8,
        src: "./gh-baby-8.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 9,
        src: "./gh-baby-9.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 10,
        src: "./gh-baby-10.webp",
        title: "Áo Polo Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 11,
        src: "./gh-baby-11.webp",
        title: "Quần Kaki Trẻ Em",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
    {
        id: 12,
        src: "./gh-baby-12.webp",
        title: "Quần Short Bé Trai",
        actualPrice: "250.000",
        oldPrice: "300.000",
    },
];